use std::sync::Arc;

use crate::{
    Engine, Extent3d, Format, GraphImage, Image, ImageDesc, ImageDimension, ImageUsage,
    RenderFrame, Result,
};

/// Controls when a procedural texture should regenerate its pixels.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ProceduralTextureUpdatePolicy {
    /// Upload once, then keep registering the same image every frame.
    Once,
    /// Upload when created and after [`CpuProceduralTexture2d::request_regenerate`] is called.
    OnRequest,
    /// Upload on every call to [`CpuProceduralTexture2d::prepare`].
    EveryFrame,
}

/// Serializable CPU procedural texture recipes for common generated assets.
#[derive(Clone, Debug, PartialEq)]
pub enum ProceduralTextureRecipe {
    Checker {
        tile_size: u32,
        color_a: [u8; 4],
        color_b: [u8; 4],
    },
    RadialMask {
        inner_radius: f32,
        outer_radius: f32,
        color: [u8; 4],
    },
    HorizontalRamp {
        left: [u8; 4],
        right: [u8; 4],
    },
}

impl ProceduralTextureRecipe {
    pub fn sample(&self, x: u32, y: u32, width: u32, height: u32, generation: u64) -> [u8; 4] {
        let _ = generation;
        match *self {
            Self::Checker {
                tile_size,
                color_a,
                color_b,
            } => {
                let tile_size = tile_size.max(1);
                let tile = (x / tile_size + y / tile_size) & 1;
                if tile == 0 { color_a } else { color_b }
            }
            Self::RadialMask {
                inner_radius,
                outer_radius,
                color,
            } => {
                let width = width.max(1) as f32;
                let height = height.max(1) as f32;
                let uv = [
                    (x as f32 + 0.5) / width * 2.0 - 1.0,
                    (y as f32 + 0.5) / height * 2.0 - 1.0,
                ];
                let distance = (uv[0] * uv[0] + uv[1] * uv[1]).sqrt();
                let t = smoothstep(outer_radius, inner_radius, distance);
                [
                    (color[0] as f32 * t).round().clamp(0.0, 255.0) as u8,
                    (color[1] as f32 * t).round().clamp(0.0, 255.0) as u8,
                    (color[2] as f32 * t).round().clamp(0.0, 255.0) as u8,
                    (color[3] as f32 * t).round().clamp(0.0, 255.0) as u8,
                ]
            }
            Self::HorizontalRamp { left, right } => {
                let denom = width.saturating_sub(1).max(1) as f32;
                let t = x as f32 / denom;
                lerp_rgba8(left, right, t)
            }
        }
    }
}

type CpuFillFn = dyn Fn(u32, u32, u32, u32, u64) -> [u8; 4] + Send + Sync + 'static;

/// A persistent 2-D texture generated by CPU code and registered into render frames by name.
///
/// The backing image is created once with `SAMPLED | COPY_DST` usage. Calling
/// [`prepare`](Self::prepare) registers the image for reflected shader bindings
/// and uploads fresh pixels only when its update policy requires it.
pub struct CpuProceduralTexture2d {
    name: String,
    image: Image,
    width: u32,
    height: u32,
    policy: ProceduralTextureUpdatePolicy,
    dirty: bool,
    generation: u64,
    fill: Arc<CpuFillFn>,
}

impl CpuProceduralTexture2d {
    pub fn new_rgba8(
        engine: &Engine,
        name: impl Into<String>,
        width: u32,
        height: u32,
        policy: ProceduralTextureUpdatePolicy,
        fill: impl Fn(u32, u32, u32, u32, u64) -> [u8; 4] + Send + Sync + 'static,
    ) -> Result<Self> {
        let name = name.into();
        let image = engine.create_image(ImageDesc {
            dimension: ImageDimension::D2,
            extent: Extent3d {
                width,
                height,
                depth: 1,
            },
            mip_levels: 1,
            layers: 1,
            samples: 1,
            format: Format::Rgba8Unorm,
            usage: ImageUsage::SAMPLED | ImageUsage::COPY_DST,
            transient: false,
            clear_value: None,
            debug_name: Some("cpu procedural texture"),
        })?;
        let _ = image.set_debug_name(&format!("cpu-procedural-{name}"));
        Ok(Self {
            name,
            image,
            width,
            height,
            policy,
            dirty: true,
            generation: 0,
            fill: Arc::new(fill),
        })
    }

    pub fn from_recipe_rgba8(
        engine: &Engine,
        name: impl Into<String>,
        width: u32,
        height: u32,
        policy: ProceduralTextureUpdatePolicy,
        recipe: ProceduralTextureRecipe,
    ) -> Result<Self> {
        Self::new_rgba8(
            engine,
            name,
            width,
            height,
            policy,
            move |x, y, w, h, generation| recipe.sample(x, y, w, h, generation),
        )
    }

    pub fn prepare(&mut self, frame: &RenderFrame) -> Result<GraphImage> {
        let should_regenerate =
            self.dirty || matches!(self.policy, ProceduralTextureUpdatePolicy::EveryFrame);

        if should_regenerate {
            let fill = Arc::clone(&self.fill);
            let width = self.width;
            let height = self.height;
            let generation = self.generation;
            let image = frame.update_texture_2d(&self.name, &self.image, move |x, y| {
                fill(x, y, width, height, generation)
            })?;
            self.generation = self.generation.saturating_add(1);
            self.dirty = false;
            Ok(image)
        } else {
            frame.import_image(&self.name, &self.image)
        }
    }

    pub fn request_regenerate(&mut self) {
        self.dirty = true;
    }

    pub fn set_policy(&mut self, policy: ProceduralTextureUpdatePolicy) {
        self.policy = policy;
        if matches!(policy, ProceduralTextureUpdatePolicy::Once) && self.generation == 0 {
            self.dirty = true;
        }
    }

    pub fn image(&self) -> &Image {
        &self.image
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn generation(&self) -> u64 {
        self.generation
    }
}

fn smoothstep(edge0: f32, edge1: f32, x: f32) -> f32 {
    let t = ((x - edge0) / (edge1 - edge0).max(f32::EPSILON)).clamp(0.0, 1.0);
    t * t * (3.0 - 2.0 * t)
}

fn lerp_rgba8(a: [u8; 4], b: [u8; 4], t: f32) -> [u8; 4] {
    [
        lerp_u8(a[0], b[0], t),
        lerp_u8(a[1], b[1], t),
        lerp_u8(a[2], b[2], t),
        lerp_u8(a[3], b[3], t),
    ]
}

fn lerp_u8(a: u8, b: u8, t: f32) -> u8 {
    (a as f32 + (b as f32 - a as f32) * t.clamp(0.0, 1.0))
        .round()
        .clamp(0.0, 255.0) as u8
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checker_recipe_alternates_tiles() {
        let recipe = ProceduralTextureRecipe::Checker {
            tile_size: 2,
            color_a: [1, 2, 3, 4],
            color_b: [5, 6, 7, 8],
        };
        assert_eq!(recipe.sample(0, 0, 8, 8, 0), [1, 2, 3, 4]);
        assert_eq!(recipe.sample(2, 0, 8, 8, 0), [5, 6, 7, 8]);
        assert_eq!(recipe.sample(2, 2, 8, 8, 0), [1, 2, 3, 4]);
    }

    #[test]
    fn horizontal_ramp_reaches_endpoints() {
        let recipe = ProceduralTextureRecipe::HorizontalRamp {
            left: [0, 10, 20, 30],
            right: [100, 110, 120, 130],
        };
        assert_eq!(recipe.sample(0, 0, 3, 1, 0), [0, 10, 20, 30]);
        assert_eq!(recipe.sample(2, 0, 3, 1, 0), [100, 110, 120, 130]);
    }
}
